### ISSUE TITLE
AO still active  but  not in inventory after #18 happend

### ISSUE THREAD

**Issue by Ana-Green** [Virtual-Universe/Virtual-Universe-Early-Dev#19] opened 2019-05-28 08:18 UTC
AO still active but not in inventory after #18 happened this is somehow related to #18 after that last issue the AO was still active but not in the inventory. [  Try to relog to  see if the AO is back ] 
Post that here: after a relog is the AO  back in my inventory (visible).

Regards,
Ana Green

**Comment by NoahStarfinder** [comment] 2019-05-28 17:10
Good afternoon,

I am going to accept this one as a potential bug.  However, until we know if this really is being caused by issue #18 I am not going to mark this as a bug just yet.  The reason is if this is related to issue 18 then it should resolve itself when we fix that issue once and for all.  Labeling as question until we have a better understanding as to what is causing thisr.

Best regards,
Noah Starfinder
Governing Body Vice Chair (North America)
Core Developer
Work Group Member
Grid Architecture Development Work Group
In Galaxy Services and Features Development, Maintenance
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2019-06-06 22:40
Closing because the new layout and cleaned up code makes this issue moot.

**Closed as completed by emperorstarfinder** 2019-06-06 22:40 UTC
Labels: Question
