### ISSUE TITLE
Issues with Profiles and Search

### ISSUE THREAD

**Issue by Ana-Green** [Virtual-Universe/Virtual-Universe-Early-Dev#10] opened 2019-05-03 02:07 UTC
I fill this in for my Dad Frank,  1) he used one simulator to use that on OSGrid, 2) If he logs on and teleports to that regions he noticed that scripts did not work. 2) Profile Picture doesn't show up, 2) About does not show up is empty. 3) Picks do not work you do not see them created on LBSA, and you can not create any new one on the region where Virtual-Universe run, as soon as you teleport to a region what runs 9.1 everything works again. to be sure I will add two files the log file and the Opensim.ini file in case Dad made a typo.

Daughter from Frank,
Ana    

[Virtual Universe.zip](https://github.com/Virtual-Universe/Virtual-Universe-NXG/files/3140462/Virtual.Universe.zip)

**Comment by NoahStarfinder** [comment] 2019-05-03 17:43
Good afternoon,

I will need to look into this further as I am not to familiar with OSGrid as I don't have any regions there personally.  However, after a preliminary review of the logs and the ini file provided, the following configuration issues do jump out at me:

`;# {ExternalHostNameForLSL} {} {Hostname to use for HTTP-IN URLs. This should be reachable from the internet.} {}
    ;; Hostname to use in llRequestURL/llRequestSecureURL
    ;; if not defined - llRequestURL/llRequestSecureURL are disabled
    ; UNCOMMENT AND SET THIS TO YOUR EXTERNAL OR LOCAL ADDRESS TO ENABLE AS NEEDED
    ;ExternalHostNameForLSL = 127.0.0.1
`
under the [Network] section this should be uncommented and pointed to the external hostname for your lsl scripts.  (i.e. your region or whatever external host name for LSL that OSGrid is telling you to use).

The other issue here appears to be that jOpenSimProfile is being enabled though it is not sitting in the configuration file as enabled.  As far as I am aware OSGrid does not use jOpenSim modules so the builtin profile will be just fine.  It is likely that this is causing some problems with the database.

I will need to look at this further.  Please provide the GridHyperGrid.ini and osslEnable.ini for further review.

@BritanyannStarfinder I am referring this to you for review as well as there does appear to be an issue in the scripting engine that may result in the need for adjustments.

Noah Starfinder 
Governing Body Vice Chair (North America)
Core Developer
In Galaxy Services and Features Development, Maintenance
Second Galaxy Development Team

**Comment by Ana-Green** [comment] 2019-05-03 22:54
Yes of course, as far I know Dad told me only that the previous release did work at OSGrid, the reason why he is not posting it himself is that he is sick now for 3 years, anyway here are the requested files.

With Respect,  
Ana
     
[config-include.zip](https://github.com/Virtual-Universe/Virtual-Universe-NXG/files/3143740/config-include.zip)

**Comment by emperorstarfinder** [comment] 2019-05-07 14:28
NOTE: this message is from Noah and not me.  Apparently our internal system thinks it was from Emperor Starfinder inaccurately.

Good morning,

After further review, I suspect the issue is the jOpenSim Profiles and Groups causing the issues.  As long as your using the configurations recommended by OSGrid you should be okay.  Because our new frontend is coming and will handle all the relative functions that it should, jOpenSim modules will not be needed.

jOpenSim modules have been slated for removal.  Once they are removed you may, however, need to start with a clean database for your osgrid region.

Noah Starfinder
Governing Body Vice Chair (North America)
Core Developer
In Galaxy Services and Features Development, Maintenance
Second Galaxy Development Team

**Comment by BritanyannStarfinder** [comment] 2019-05-10 15:39
Good morning,

Some of this issue is being caused oddly by jOpenSimProfile and jOpenSimSearch.  It is possible that there were pieces missing, including the end-user not using Joomla with the required dependencies for JOpenSim to work with Joomla.  In any event I have removed these two ;modules to ensure they do not cause trouble.

Looking at the logs I also noticed an issue with Gloebits which I suspect has to do with the scripting engine which I will look at.  

As Noah Stated previously in the [Network] section under the following:

`;# {ExternalHostNameForLSL} {} {Hostname to use for HTTP-IN URLs. This should be reachable from the internet.} {} ;; Hostname to use in llRequestURL/llRequestSecureURL ;; if not defined - llRequestURL/llRequestSecureURL are disabled ; UNCOMMENT AND SET THIS TO YOUR EXTERNAL OR LOCAL ADDRESS TO ENABLE AS NEEDED ;ExternalHostNameForLSL = 127.0.0.1`

you need to ensure you replace:

`;ExternalHostNameForLSL = 127.0.0.1`

with: 

`ExternalHostNameForLSL = ${Const|BaseHostname}`

This will ensure the services know the External Host Name for the LSL scripts.  By default Virtual Universe has this uncommented in the OpenSim.ini file.  Therefore please be sure you are using the correct version of the OpenSim.ini file for your regions and make the changes required by OSGrid.

Best Regards,

Britanyann Starfinder
Core Developer
Scripting Engine Development, Maintenance
Second Galaxy Development Team

**Comment by Ana-Green** [comment] 2019-05-10 23:53
I still waiting for the OpenSim search to become active, like the search for regions names, for example, I did try to add  OpenSimSearch_ver0.4 to it, but it won't compile. :(

**Comment by NoahStarfinder** [comment] 2019-05-12 13:03
Good morning,

OpenSimSearch is already in the OpenSim.Addons directory and does compile.  Adding a different version would only cause conflicts with that.

When the full built-in version of search does get pushed to the repository it likely will not work with OSGrid.  Please keep in mind our primary focus with Virtual Universe is to provide a fully functional and stable grid architecture.  Because there are going to be many changes there will always be a possibility (at least in the short term) that Virtual Universe will not work with OSGrid or other grids that allow you to connect your regions to their grid that run OpenSim.

Noah Starfinder
Governing Body Vice Chair (North America)
Core Developer
In Galaxy Services and Features Development, Maintenance
Second Galaxy Development Team

**Comment by Ana-Green** [comment] 2019-05-16 16:59
Good Evening

You said OpenSearch is already in the OpenSim Add-ons directory and does compile. Adding a different version would only cause conflicts with that. What version is that as  I cannot find any openSimSearch in the Virtual-Universe NXG version I downloaded, My  Dad's  Grid is down, choices are using OpenSim 0.9.0 or  0.9.0.1 or 0.9.1 or Virtual-Universe NXG [ Last version ]. But I downloaded this version but do not find any OpenSearch in OpenSim Add-ons. I see in Virtual-Universe-NXG/OpenSim/Addons/ only Groups, MutelistModule and OfflineIM, but no OpenSearch? Then in the config file OpenSim.ini there is no [Search] section. or maybe I am young and blind or dumb.

Ana Green 
Intel and CISCO, 
SL/LL BetaGrid Tester, 
Firestorm Beta Tester. 
started at 9/12/2018 at NASA.

**Comment by Ana-Green** [comment] 2019-05-18 20:26
OpenSim Search is still not working I did a side by side test Virtual-Universe NXG and Opensim 0.9.1.0. Search did work with OpenSim 0.9.1.0  but not with Virtual-Universe NXG.

Reference: 51aa57f

Regards,
Ana Green
Intel and CISCO,
SL/LL BetaGrid Tester,
Firestorm Beta Tester.
Started at 9/12/2018 at NASA.

**Comment by emperorstarfinder** [comment] 2019-08-23 23:22
Closing as we will have a builtin search module and this is no longer an issue.

**Closed as completed by emperorstarfinder** 2019-08-23 23:22 UTC
Labels: Bug, Review for Compatibility Mod
