### ISSUE TITLE
Will not compile due wrong name

### ISSUE THREAD

**Issue by Ana-Green** [Virtual-Universe/Virtual-Universe-Early-Dev#25] opened 2019-07-28 23:51 UTC
After you run "runprebuild.bat" it creates "compile.bat" and "Opensim.sln" but the content of "compile.bat" looks like  this :  C:\Program\msbuild Universe.sln 

However there  has be no  Universe.sln created but a Opensim.sln, thus it will not compile unless you change the file "compile.bat" from C:\Program\msbuild Universe.sln into C:\Program\msbuild opensim.sln 

Regards,
Ana Green

**Comment by Ana-Green** [comment] 2019-07-28 23:57
**Correction**, while OpenSim.sln in the folder and compile.bat changed into C:\Program\msbuild OpenSim.sln, it still doesn't compile, and  no there is no Universe.sln. 

Regards,
Ana Green

**Comment by Ana-Green** [comment] 2019-07-29 00:10
Due build using Microsoft Visual Studio I got 577 errors, most errors where or are related to 'could not be found' with that said several files could not be found. 

Regards,
Ana Green

**Comment by BruceStarfinder** [comment] 2019-07-29 14:00
Good morning,

First, you can safely disregard the Compile.bat file.  That is there at the moment as a placeholder to remind Core Developers of a few things.  It won't build intentionally so that is not really a problem.  If you have Visual Studios or Mono Develop installed you do not need to run the MSBuild command via the command line.  The build process including the steps to build will be changing in the near future which ultimately will remove the Prebuild step.

The errors seen during the build are being caused by an underlying commit.  Because we do have a big cleanup commit on the way which should be happening in the next week or two, I recommend waiting for that commit as there will be a lot of changes as we clean up the codebase and get rid of the commented out code.  Additionally, these errors have already been corrected in that commit.

Best Regards,
Bruce Starfinder
Core Developer
Work Group member
Grid Architecture Development Work Group
Grid Architecture Development, Database Development, Maintenance
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2019-08-23 23:21
Closing as this is now resolved.

**Closed as completed by emperorstarfinder** 2019-08-23 23:21 UTC
