### ISSUE TITLE
Status off/online 

### ISSUE THREAD

**Issue by Ana-Green** [Virtual-Universe/Virtual-Universe-Early-Dev#7] opened 2019-04-07 11:39 UTC
Hello all,

I tested VU on OSGrid, if I look in the listing status what tells or people are online or not  it shows  me Status: Unkown 

Repro: connect your region simulator to OSGrid, once the region created, login into OSGrid. 
Teleport to your test region (make  home  from it)  goto LBSA join some  groups TP home and  you'll see  that all groups  will  show Status: Unkown 

Daughter from Frank, 
Ana

**Comment by BriaKallistaStarfinder** [comment] 2019-04-07 12:50
Aloha,

Can you please delete the logs in the bin folder (i.e. OpenSim.txt, 
ConsoleHistory.txt, Robust.txt, etc.) and then set the log levels in the 
console via command set log level all.  This will allow us to record all 
of the info and errors (if any errors) that might show up on the 
console.  Then try to reproduce the steps and provide us a copy of the 
newly created log files along with the configurations used so we can 
test it internally.

It should be noted, that while we will be ensuring compatibility with 
OpenSim and its various forks and derivatives, because Virtual Universe 
is the open source project arm of the Second Galaxy Development Team it 
will not eventually work like OpenSim and there will always be 
differences between OpenSim and Virtual Universe including things that 
will not necessarily be compatible.  Ultimately, Virtual Universe will 
work like Second Galaxy's Proprietary Grid Architecture does.


Best regards,

Briakallista Starfinder
Member Roles: Core Developer
Member Responsibilities: Roleplay lifestyles Development, Maintenance, 
Viewer Development

**Comment by Ana-Green** [comment] 2019-04-07 18:19
Ciao Briakallista

Will  do  that  only  that will be  tomorrow  

Best Regards,
Ana Green  :)

**Comment by emperorstarfinder** [comment] 2019-08-23 23:18
Closing as this issue is now out of date.

**Closed as completed by emperorstarfinder** 2019-08-23 23:18 UTC
